
[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]

venvPath = "/home/silvan/Environments/"
venv = "coco_0603"

executionEnvironments = [
  # { root = "src/lecture-exercise", venvPath = "/home/silvan/Software/miniconda3/envs", venv = "tensorflow_0501" },
  # { root = "src/ultralytics", venv = "ultra_0518" },
  { root = "src" },
]
